algoritmo "semnome"
var
    numero: inteiro
inicio
    escreval("Digite um numero inteiro dentre esses:")
    escreva("[1]; [2]; [3]; [4]; [5]; [6]; [7]: ")
    leia(numero)
    escolha numero
    caso 1
        escreva("DOMINGO")
    caso 2
        escreva("SEGUNDA")
    caso 3
        escreva("TERÇA")
    caso 4
        escreva("QUARTA")
    caso 5
        escreva("QUINTA")
    caso 6
        escreva("SEXTA")
    caso 7
        escreva("SÁBADO")
    fimescolha
fimalgoritmo
